### ISSUE TITLE
作者你很好，请问如何申请公司，你是自己注册得嘛？

### ISSUE THREAD

**Issue by Mayandev** [xuhuai66/used-book-pro#4]

**Comment by xiexingen** [comment]
我有朋友做这种代办、代记账的

**Comment by xuhuai66** [comment]
是的



---原始邮件---
发件人: "Gary.Xie"<notifications@github.com&gt;
发送时间: 2020年4月10日(周五) 上午9:23
收件人: "xuhuai66/used-book-pro"<used-book-pro@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [xuhuai66/used-book-pro] 作者你很好，请问如何申请公司，你是自己注册得嘛？ (#4)




 
我有朋友做这种代办、代记账的

**Comment by xiexingen** [comment]
> 是的
> […](#)
> ---原始邮件--- 发件人: "Gary.Xie"<notifications@github.com&gt; 发送时间: 2020年4月10日(周五) 上午9:23 收件人: "xuhuai66/used-book-pro"<used-book-pro@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [xuhuai66/used-book-pro] 作者你很好，请问如何申请公司，你是自己注册得嘛？ (#4) 我有朋友做这种代办、代记账的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

一般自己公司有财务啥的就自己公司弄，如果没有 一般是找个专门代理记账的公司办理的 省心省事

**Comment by Mayandev** [comment]
> > 是的
> > […](#)
> > --- 原始邮件 --- 发件人: "Gary.Xie"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020 年 4 月 10 日 (周五) 上午 9:23 收件人: "xuhuai66/used-book-pro"<[used-book-pro@noreply.github.com](mailto:used-book-pro@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: Re: [xuhuai66/used-book-pro] 作者你很好，请问如何申请公司，你是自己注册得嘛？ (#4) 我有朋友做这种代办、代记账的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> 一般自己公司有财务啥的就自己公司弄，如果没有 一般是找个专门代理记账的公司办理的 省心省事

价格一般是多少？

**Comment by xiexingen** [comment]
> > > 是的
> > > […](#)
> > > --- 原始邮件 --- 发件人: "Gary.Xie"<[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020 年 4 月 10 日 (周五) 上午 9:23 收件人: "xuhuai66/used-book-pro"<[used-book-pro@noreply.github.com](mailto:used-book-pro@noreply.github.com)>; 抄送: "Subscribed"<[subscribed@noreply.github.com](mailto:subscribed@noreply.github.com)>; 主题: Re: [xuhuai66/used-book-pro] 作者你很好，请问如何申请公司，你是自己注册得嘛？ (#4) 我有朋友做这种代办、代记账的 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> > 
> > 
> > 一般自己公司有财务啥的就自己公司弄，如果没有 一般是找个专门代理记账的公司办理的 省心省事
> 
> 价格一般是多少？

我也没注册过 要不给你联系方式 你自己问问吧 是我一个玩的比较好的朋友的 还是靠谱的 
https://www.52dibo.com/
